[package]
name = "datadog-logs"
version = "0.1.0"
authors = ["rdkt13 <rdkt13@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniserde = { version = "0.1.13" }
attohttpc = { version = "0.15.0", features = ["tls", "compress"] }
log = { version = "0.4.11" }